version: '3.7'
services:
  bludit:
    image: deburau/bludit:latest
    container_name: bludit
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./html:/usr/share/nginx/html
    environment:
      - SOURCE_ARCHIVE
      - UPGRADE
